In [1]:
import numpy as np

**array operaton**

***arithmetic operation***

In [5]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])


In [6]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [7]:
a1- a2

array([-5, -5, -5, -5, -5])

In [8]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1 // a2

array([0, 0, 0, 0, 0])

In [11]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

In [18]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

broadcosting

In [13]:
l = [10,20,30,40]
arr =np.array(l)

In [15]:
arr+10

array([20, 30, 40, 50])

deep and shallow copy

In [30]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
slice = a[:5]
slice = slice * 10
slice

array([10, 20, 30, 40, 50])

In [32]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

+++++++++++++++++++++++

In [33]:
a 
b=a
b[0]=99
print(a)

[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [39]:
t= np.arange(1,21)
c = t.copy()
c[0] = 99
print(t)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[99  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


matrix operation 

In [43]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])


In [44]:
A

array([[1, 2],
       [3, 4]])

In [45]:
B

array([[5, 6],
       [7, 8]])

In [47]:
A @ B

array([[19, 22],
       [43, 50]])

or


In [48]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

transpose of array

In [50]:
A

array([[1, 2],
       [3, 4]])

trasp


In [49]:
A.T

array([[1, 3],
       [2, 4]])

**Advance array manipulation**

stricking array


In [53]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [59]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

splitting array

In [66]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [69]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]