In [1]:
import numpy as np
rohit= [12,12,334,45,56,67]
print(np.sort(rohit))

[ 12  12  45  56  67 334]


In [2]:
arr =np.array([12,12,23,34,45,45])
print(arr)


[12 12 23 34 45 45]


In [7]:
a =[1,2,3,4,5,"rohit"]
print(type(a))
print(a)

<class 'list'>
[1, 2, 3, 4, 5, 'rohit']


In [5]:
ae = np.array(a)
print(ae)
print(type(ae))

['1' '2' '3' '4' '5' 'rohit']
<class 'numpy.ndarray'>


In [12]:
l = [[1,2,3],[4,5,6],[7,8,9]]
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [13]:
p = np.array(l)
print(p)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
d= np.arange(1,11)
print(d)
print(type(d))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [18]:
d= np.arange(2,11,2)
print(d)
print(type(d))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [21]:
t= np.zeros((6,6))
print(t)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [22]:
y= np.ones((4,4))
print(y)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [23]:
arr =np.linspace(1,5,2)
arr

array([1., 5.])

##random 


In [25]:
np.random.rand(10)

array([0.08194597, 0.63525715, 0.59267137, 0.46855891, 0.72150621,
       0.91890614, 0.05663856, 0.35496383, 0.52264896, 0.03847322])

In [26]:
np.random.randn(10)

array([ 0.87149438,  0.6723353 ,  1.18081691, -1.30409977,  0.39741157,
        0.32299426,  0.69370342, -0.42502266,  0.25292882,  0.70889599])

In [32]:
p = np.random.randint(10,100,10)
print(p)

[19 81 63 86 14 18 17 81 74 69]


**array attributes**

In [33]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
arr.shape

(3, 3)

In [36]:
arr.size

9

In [37]:
arr.dtype

dtype('int64')

@array Methods

In [38]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
arr.min()

np.int64(1)

In [40]:
arr.max()

np.int64(9)

In [41]:
arr.sum()

np.int64(45)

sum on column 


In [45]:
np.sum(arr,axis=0)


array([12, 15, 18])

sum on row

In [46]:
np.sum(arr,axis=1)

array([ 6, 15, 24])

mean


In [47]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.mean()

np.float64(5.0)

In [48]:
arr.std()

np.float64(2.581988897471611)

index number of maximum number


In [49]:
arr.argmax()

np.int64(8)

index number of minimum number

In [52]:
arr.argmin()

np.int64(0)

***reshaping and resizing***

In [54]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
arr =arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])