***numpy indexing and slicing of vectors***


In [1]:
import numpy as np

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[6]

np.int64(17)

In [13]:
arr[1:7]

array([12, 13, 14, 15, 16, 17])

In [14]:
arr[:5]

array([11, 12, 13, 14, 15])

In [15]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [20]:
arr[1::2]

array([12, 14, 16, 18, 20])

***numpy indexing and slicing of matrix***

In [23]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [28]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [29]:
arr[0:4]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
print(arr[0,0])


1


In [33]:
arr[0,2]

np.int64(3)

slicing


In [37]:
slice = arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [39]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [40]:
arr[:,3]

array([ 4,  9, 14, 19, 24, 29])

**BOOLERN indexing**

In [51]:
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [52]:
bool_index= arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [53]:
arr = arr[bool_index]


In [54]:
arr

array([12, 14, 16, 18, 20])